// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application_proto.proto

package com.mk.framework.context;

public final class ApplicationProto {
  private ApplicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApplicationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mk.framework.context.ApplicationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string classname = 2;</code>
     */
    java.lang.String getClassname();
    /**
     * <code>string classname = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassnameBytes();

    /**
     * <code>string ibrokerobject = 3;</code>
     */
    java.lang.String getIbrokerobject();
    /**
     * <code>string ibrokerobject = 3;</code>
     */
    com.google.protobuf.ByteString
        getIbrokerobjectBytes();
  }
  /**
   * Protobuf type {@code com.mk.framework.context.ApplicationData}
   */
  public  static final class ApplicationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mk.framework.context.ApplicationData)
      ApplicationDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplicationData.newBuilder() to construct.
    private ApplicationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplicationData() {
      key_ = "";
      classname_ = "";
      ibrokerobject_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApplicationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              classname_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ibrokerobject_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mk.framework.context.ApplicationProto.internal_static_com_mk_framework_context_ApplicationData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mk.framework.context.ApplicationProto.internal_static_com_mk_framework_context_ApplicationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mk.framework.context.ApplicationProto.ApplicationData.class, com.mk.framework.context.ApplicationProto.ApplicationData.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object classname_;
    /**
     * <code>string classname = 2;</code>
     */
    public java.lang.String getClassname() {
      java.lang.Object ref = classname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classname_ = s;
        return s;
      }
    }
    /**
     * <code>string classname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassnameBytes() {
      java.lang.Object ref = classname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IBROKEROBJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object ibrokerobject_;
    /**
     * <code>string ibrokerobject = 3;</code>
     */
    public java.lang.String getIbrokerobject() {
      java.lang.Object ref = ibrokerobject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ibrokerobject_ = s;
        return s;
      }
    }
    /**
     * <code>string ibrokerobject = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIbrokerobjectBytes() {
      java.lang.Object ref = ibrokerobject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ibrokerobject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getClassnameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, classname_);
      }
      if (!getIbrokerobjectBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ibrokerobject_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getClassnameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, classname_);
      }
      if (!getIbrokerobjectBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ibrokerobject_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mk.framework.context.ApplicationProto.ApplicationData)) {
        return super.equals(obj);
      }
      com.mk.framework.context.ApplicationProto.ApplicationData other = (com.mk.framework.context.ApplicationProto.ApplicationData) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getClassname()
          .equals(other.getClassname());
      result = result && getIbrokerobject()
          .equals(other.getIbrokerobject());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassname().hashCode();
      hash = (37 * hash) + IBROKEROBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getIbrokerobject().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mk.framework.context.ApplicationProto.ApplicationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mk.framework.context.ApplicationProto.ApplicationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mk.framework.context.ApplicationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mk.framework.context.ApplicationData)
        com.mk.framework.context.ApplicationProto.ApplicationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mk.framework.context.ApplicationProto.internal_static_com_mk_framework_context_ApplicationData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mk.framework.context.ApplicationProto.internal_static_com_mk_framework_context_ApplicationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mk.framework.context.ApplicationProto.ApplicationData.class, com.mk.framework.context.ApplicationProto.ApplicationData.Builder.class);
      }

      // Construct using com.mk.framework.context.ApplicationProto.ApplicationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        classname_ = "";

        ibrokerobject_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mk.framework.context.ApplicationProto.internal_static_com_mk_framework_context_ApplicationData_descriptor;
      }

      @java.lang.Override
      public com.mk.framework.context.ApplicationProto.ApplicationData getDefaultInstanceForType() {
        return com.mk.framework.context.ApplicationProto.ApplicationData.getDefaultInstance();
      }

      @java.lang.Override
      public com.mk.framework.context.ApplicationProto.ApplicationData build() {
        com.mk.framework.context.ApplicationProto.ApplicationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mk.framework.context.ApplicationProto.ApplicationData buildPartial() {
        com.mk.framework.context.ApplicationProto.ApplicationData result = new com.mk.framework.context.ApplicationProto.ApplicationData(this);
        result.key_ = key_;
        result.classname_ = classname_;
        result.ibrokerobject_ = ibrokerobject_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mk.framework.context.ApplicationProto.ApplicationData) {
          return mergeFrom((com.mk.framework.context.ApplicationProto.ApplicationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mk.framework.context.ApplicationProto.ApplicationData other) {
        if (other == com.mk.framework.context.ApplicationProto.ApplicationData.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getClassname().isEmpty()) {
          classname_ = other.classname_;
          onChanged();
        }
        if (!other.getIbrokerobject().isEmpty()) {
          ibrokerobject_ = other.ibrokerobject_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mk.framework.context.ApplicationProto.ApplicationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mk.framework.context.ApplicationProto.ApplicationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object classname_ = "";
      /**
       * <code>string classname = 2;</code>
       */
      public java.lang.String getClassname() {
        java.lang.Object ref = classname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          classname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string classname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassnameBytes() {
        java.lang.Object ref = classname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          classname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string classname = 2;</code>
       */
      public Builder setClassname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        classname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string classname = 2;</code>
       */
      public Builder clearClassname() {
        
        classname_ = getDefaultInstance().getClassname();
        onChanged();
        return this;
      }
      /**
       * <code>string classname = 2;</code>
       */
      public Builder setClassnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        classname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ibrokerobject_ = "";
      /**
       * <code>string ibrokerobject = 3;</code>
       */
      public java.lang.String getIbrokerobject() {
        java.lang.Object ref = ibrokerobject_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ibrokerobject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ibrokerobject = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIbrokerobjectBytes() {
        java.lang.Object ref = ibrokerobject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ibrokerobject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ibrokerobject = 3;</code>
       */
      public Builder setIbrokerobject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ibrokerobject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ibrokerobject = 3;</code>
       */
      public Builder clearIbrokerobject() {
        
        ibrokerobject_ = getDefaultInstance().getIbrokerobject();
        onChanged();
        return this;
      }
      /**
       * <code>string ibrokerobject = 3;</code>
       */
      public Builder setIbrokerobjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ibrokerobject_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mk.framework.context.ApplicationData)
    }

    // @@protoc_insertion_point(class_scope:com.mk.framework.context.ApplicationData)
    private static final com.mk.framework.context.ApplicationProto.ApplicationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mk.framework.context.ApplicationProto.ApplicationData();
    }

    public static com.mk.framework.context.ApplicationProto.ApplicationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplicationData>
        PARSER = new com.google.protobuf.AbstractParser<ApplicationData>() {
      @java.lang.Override
      public ApplicationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApplicationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApplicationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mk.framework.context.ApplicationProto.ApplicationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mk_framework_context_ApplicationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mk_framework_context_ApplicationData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027application_proto.proto\022\030com.mk.framew" +
      "ork.context\"H\n\017ApplicationData\022\013\n\003key\030\001 " +
      "\001(\t\022\021\n\tclassname\030\002 \001(\t\022\025\n\ribrokerobject\030" +
      "\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mk_framework_context_ApplicationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mk_framework_context_ApplicationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mk_framework_context_ApplicationData_descriptor,
        new java.lang.String[] { "Key", "Classname", "Ibrokerobject", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
